# Updated Railway Database Credentials
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:55302/railway
spring.datasource.username=root
spring.datasource.password=OVScByPaVdcMVfTDHDtELHMcwFWFiDSp

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
=======
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
>>>>>>> 76fbaeb1d09590787971f65cf6d98e2c8f4135a0
